### ISSUE TITLE
d2l-switch-visibility visual bug in RTL Arabic in the new Content Experience

### ISSUE THREAD

**Issue by mostlyfabulous** [BrightspaceUI/core#1019]
### The visibility switch is too narrow when rendered in the new Content Experience:
_Not sure if this issue should be logged here._
 
**Site found on: cd2021227101**
**BSI: 20.21.2-26**
Legacy Content experience, FACE Assignments and FACE Quizzing display fine.

**Main view**:
![image](https://user-images.githubusercontent.com/15062048/103379727-777d0380-4a9b-11eb-8805-126c93ae4cae.png)
![image](https://user-images.githubusercontent.com/15062048/103379747-89f73d00-4a9b-11eb-8a51-87db39c093ff.png)

**New module creation:**
![image](https://user-images.githubusercontent.com/15062048/103379626-1ce3a780-4a9b-11eb-8e29-83e7645e93bc.png)

**Comment by dlockhart** [comment]
I think this is just the RTL defect that @dbatiste [recently fixed last week](https://github.com/BrightspaceUI/core/pull/1017)?

**Comment by mostlyfabulous** [comment]
I believe that RTL fix to `core` is included with BSI: `20.21.2-26`?
https://github.com/Brightspace/brightspace-integration/commit/fa0a7ddf7293f199808ba58ac5bb3758abeab3c6

The bug still shows up on **cd2021227110**; BSI: `20.21.2-27`
![image](https://user-images.githubusercontent.com/15062048/103383339-368aec00-4aa7-11eb-8a98-fb25380193e3.png)

**Comment by dbatiste** [comment]
This looks like a different issue.  There might be some property that is being inherited that is making this layout different, but only in the RTL case.  Certainly unexpected though.

Also, slight aside - this is not the visibility switch, this is just the standard switch.  I think this may become a consistency/usability issue since other things that control visibility use `d2l-switch-visibility` (which has different icons).  If this represents visibility, we really should use that component instead of the generic `d2l-switch`.

**Comment by dbatiste** [comment]
This is because the RTL styles aren't being applied due to the [ifrau client](https://github.com/Brightspace/ifrau/blob/master/src/plugins/sync-lang/client.js#L9) only setting `dir="rtl"` on the `body`.  All of our components (at least in core) rely on the attribute on `html`.  I will make an update to ifrau to apply it to both, in the same way that the LMS does for the host page.

**Comment by dbatiste** [comment]
@mostlyfabulous : note, the current usage of the `d2l-switch` applies `aria-labelledby` to `d2l-switch`.  The reason this is not accessible is because the focus is applied to an element within the shadowDOM (not the host element), which has the correct Aria role etc.  

Please see [d2l-switch properties](https://github.com/BrightspaceUI/core/tree/master/components/switch#d2l-switch) for correct usage, which requires the `text` property.  The position of the text can be controlled using `text-position`.  The separate eye icon becomes redundant if `d2l-switch-visibility` is used.

**Comment by mostlyfabulous** [comment]
Thanks for the detailed explanation behind the technicalities, learnt some new things!
