### ISSUE TITLE
Feature request: allow a multi-dimensional filter button to have custom text (`d2l-filter`)

### ISSUE THREAD

**Issue by Chebsi** [BrightspaceUI/core#2150]
Currently with multi-dimensional filters, the filter button text is "Filters" by default, and this can't be changed. The request is to allow custom text for multi-dimensional filters.

My specific use case is in our Nova project, we have many different filters but we want to bring attention to the "Skills" filter, since it's more important. So "Skills" stands out and has its own single-dimension filter. 

Beside it, we have "Other filters", which is a multi-dimensional filter, containing a bunch of other filters you can apply to the collection. Right now it has to be called "Filters", but we want it to say "Other filters". This is a quick little mockup of what's desired (the "Other filters" text)

![image](https://user-images.githubusercontent.com/1237719/156056378-8cbff74b-2efa-421d-a0d9-d29ed1000f18.png)

**Comment by geurts** [comment]
Thanks Moe, this seems reasonable to me! Are you able to wait until next week to hear back on this? Stacy will be back and we'll review this together and circle back with you.

Relatedly: Are you switching from individual filters to a multi-dimensional filter at a breakpoint? Asking because we have plans to implement overflow handling similar to what we did for d2l-overflow-group (which is for buttons). Looks like this will be tackled in early/mid April.

**Comment by Chebsi** [comment]
> Are you able to wait until next week to hear back on this?

For sure, I can certainly wait to hear back after your review.

> Are you switching from individual filters to a multi-dimensional filter at a breakpoint?

Yes! In larger viewports we have each of the "Other filters" as their own single-dimension filter. Good to know there are already plans for this.
