### ISSUE TITLE
Filter selected property is not updating ui

### ISSUE THREAD

**Issue by tenbradley** [BrightspaceUI/core#2514]
The `d2l-filter-dimension-set-value` is not being selected/deselected when the `selected` property is set in the render function.

This can be observed by inspecting the elements for the demo page. When an item is selected, `d2l-filter-dimension-set-value` does not update to have the selected attribute.

The following pr is attempting to use the `selected` property which unselects items when an item is disabled. Disabling is working, but the items are not being unselected.
https://github.com/BrightspaceHypermediaComponents/foundation-components/pull/537

**Comment by svanherk** [comment]
> This can be observed by inspecting the elements for the demo page. When an item is selected, d2l-filter-dimension-set-value does not update to have the selected attribute.

This is true, the `selected` values on the actual list items do not update the corresponding `d2l-filter-dimension-set-value` - its up to the consumer to keep them in sync after receiving the `d2l-filter-change` event.  But if the consumer changes the value of `selected` on `d2l-filter-dimension-set-value`, that _should_ update the actual list item to match (and an event won't be fired, because it was the consumer that set it, not the user).  Am I able to reproduce this on a demo if I check out your branch?

**Comment by tenbradley** [comment]
Yes. In the last demo for the `d2l-hc-filter-controller`, the steps to do this would be:
1. Select 'Physics' in the 'Department' filter.
2. Press 'Simulate Update' button.
Expected result: 'Physics' is disabled and unselected.
Actual result: 'Physics' is disabled and selected.

**Comment by svanherk** [comment]
The 'Simulate Update' button doesn't seem to do anything for me - do I maybe need some changes to the demo?  I only see changes to the actual component in your branch
