### ISSUE TITLE
Should menu shortcut keys be case-insensitive?

### ISSUE THREAD

**Issue by dlockhart** [BrightspaceUI/core#557]
Watching @svanherk's GAAD demo today made me wonder if we shouldn't be treating the printable characters in menu items in a case sensitive way? It seemed really unintuitive to me to need to know whether a menu item is "Delete" vs. "delete" to know whether to hold down shift.

[The spec](https://www.w3.org/TR/wai-aria-practices-1.1/#menu) is ambiguous:
> Any key that corresponds to a printable character (Optional): Move focus to the next menu item in the current menu whose label begins with that printable character.

Thoughts?

**Comment by cbellini** [comment]
I wasn't sure if the SHIFT key was pressed as a necessary modifier to the keyboard shortcut, or needed to match the text 🤔.

Case-insensitivity feel like a better experience and matches the experience in other platforms (e.g. Windows Explorer/Finder).

**Comment by svanherk** [comment]
> At first, I wasn't sure if the SHIFT key was pressed as a necessary modifier to the keyboard shortcut, or needed to match the text 🤔.

Yeah it was just to make sure the exact character code was passed in.  If the menu items had started with lowercase letters I could have just pressed "t".
I made sure to point it out in the demo in case people went and tried it out after, because I found it un-intuitive and @dbatiste had to point out how to get it to work

**Comment by dbatiste** [comment]
Case insensitive seems reasonable to me.
