### ISSUE TITLE
d2l-dialog not resized properly when d2l-dialog-content is too long

### ISSUE THREAD

**Issue by LubaBroitman** [BrightspaceUI/core#734]
When the message to be shown in the dialog gets long (63 characters in my case) there is a scroll bar added and the text is cut.
![image](https://user-images.githubusercontent.com/19672382/88684290-eea80900-d0b1-11ea-9f70-f62034d5f30a.png)

**Comment by dlockhart** [comment]
@LubaBroitman would you be able to apply `word-break: break-word` to your content?

Like:
```html
<d2l-dialog>
    <div style="word-break: break-word;">Content in here</div>
</d2l-dialog>
```

I'm hesitant to apply this to all dialogs as breaking in the middle of a word isn't always what we want. The issue here isn't the character count, but the fact that there isn't any whitespace in the text. We suffer from this issue everywhere in the system, and typically it's only an edge case that we run into in testing -- in reality people have spaces in their text. If you think this is a legitimate scenario for you, you should be able to just wrap your content in `word-break`.

**Comment by LubaBroitman** [comment]
I tried to add spaces to the name of the system (the message supposed to read `Are you sure you want to disable Aa Bb Cc Dd Ee Ff Gg Hh Ii Jj Kk Ll?` but it still does it.
Just to clarify: I am not too concerned about the scroll bar, I just really would like to see the message not being cut into unreadable text.
![image](https://user-images.githubusercontent.com/19672382/88704644-9bdb4b00-d0cb-11ea-9f27-02551736ec48.png)

**Comment by dlockhart** [comment]
Ok that's strange. Can you include the exact markup that ends up being rendered in the browser so that we can reproduce?

**Comment by LubaBroitman** [comment]
Here is where the code for this dialog: https://github.com/Brightspace/ipsis-admin-ui/blob/master/src/components/dialog-accept-decline.js#L9
If you would like to see it in real time, here is my VM:

- Dims link: https://dims.proddev.d2l/web/autologin.aspx?url=ltisig.devlms.brightspace.com

- My specific tool: https://ltisig.devlms.brightspace.com/d2l/im/ipsis/admin/console/integration/27/dashboard

Just try to disable/enable it (feel free to mess it up).
Thank you!

**Comment by dlockhart** [comment]
Ah I see what's going on. There's a `white-space: nowrap` that's getting inherited from here I think:
https://search.d2l.dev/xref/GitHub/Brightspace/ipsis-admin-ui/src/components/source-system-enable-disable.js?r=47d1e79c#21

If I remove that then things wrap properly in the dialog.

**Comment by maggiesazio** [comment]
That was the issue. Thanks @dlockhart
