### ISSUE TITLE
d2l-dialog not resized for mobile devises

### ISSUE THREAD

**Issue by MykolaGalian** [BrightspaceUI/core#952]
During testing on the phone (Android: Chrome)  and in dev tools (Windows: Chrome, Edge) the d2l-dialog not resized to the full screen of mobile devices. [Defect](https://rally1.rallydev.com/#/detail/defect/450971796436?fdp=true). [Test page](https://github.com/Brightspace/insights-engagement-dashboard/blob/master/demo/index.html).

![18](https://user-images.githubusercontent.com/27500223/99061371-1f9d4280-25aa-11eb-9d91-7e2e4d374a37.gif)

**Comment by dlockhart** [comment]
I investigated this a bit. The problem is actually what's behind the dialog. Your application has things on it that are forcing the window to be wider than the viewport, and the way dialogs work at low resolution is to take up `100%` of the available window.

For example, if I close the dialog you can see the things that are forcing the page wider:
![Screen Shot 2020-11-13 at 12 06 22 PM](https://user-images.githubusercontent.com/5491151/99099590-abae6a80-25a8-11eb-9c56-c19b229bbf40.png)

If you can update those charts such they responsively shrink down and don't for the page to be wider, the dialog will work correctly.

Having said that, there may be things we can change in dialog so that it doesn't break in this scenario, as it could end up being a pretty common thing. @dbatiste I played around with using `100vw` and `100vh` instead of `100%`, and this "solved" this issue -- not sure though if it might cause other problems.

**Comment by MykolaGalian** [comment]
After this PR all works well https://github.com/BrightspaceUI/core/pull/966/files
